web:
  build: .
  working_dir: /data
  command: python app2.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "8000:8000"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: mudar123
  ports:
    - "3309:3309"
